//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int student_id { get; set; }
        public string student_name { get; set; }
        public string student_sub1 { get; set; }
        public string student_sub2 { get; set; }
        public string student_sub3 { get; set; }
        public Nullable<int> student_grade1 { get; set; }
        public Nullable<int> student_grade2 { get; set; }
        public Nullable<int> student_grade3 { get; set; }
    }
}
